#encoding:utf-8

from django.forms import ModelForm
from django.forms.widgets import HiddenInput, RadioSelect
from django.contrib.admin.widgets import AdminDateWidget
from django import forms
from captura.models import *

importancia = (
			('Muy importante','Muy importante'),
			('Algo importante','Algo importante'),
			('Poco importante','Poco importante')
)

sino = (
		(1,'Si'),
		(2,'No')
)

sexo = (
		('masculino','Masculino'),
		('femenino','Femenino')
)

ce = (
		(4,4),
		(3,3),
		(2,2),
		(1,1)
)

espe = (
		('Endocrinología','Endocrinología'),
		('Neurología','Neurología')
)

pais = (
		('México','México'),
		('Colombia','Colombia')
)

def OpcionesNumericas():
	opciones = []
	for x in xrange(0,100):
		opciones.append((str(x), x)) 
		pass
	opciones.append(('999',999))
	return opciones

def DiasMes():
	opciones = []
	for x in xrange(0,32):
		opciones.append((str(x), x)) 
		pass
	opciones.append(('999',999))
	return opciones

class FrmEntrevistado(ModelForm):
	"""Formulario de enrtevistado"""
	folio_principal = forms.CharField(label="Folio", help_text='',  widget=forms.TextInput(attrs={'readonly':'readonly'}),required=False)
	monitor_clinico = forms.CharField(label="Monitor clínico", widget=forms.TextInput(attrs={'readonly':'readonly'}), help_text='' ,required=False)
	supervisor = forms.CharField(label="Supervisor", help_text='',widget=forms.TextInput(attrs={'readonly':'readonly'}) , required=False)
	fecha_llenado = forms.DateField(label="Fecha de llenado", help_text='', required=True)
	nombre_medico = forms.CharField(label="Nombre del medico", help_text='', required=False)
	especialidad = forms.ChoiceField(label="Especialidad", help_text='', choices=espe, required=False)
	pais = forms.ChoiceField(label="País", help_text='', choices=pais, required=False)
	institucion_publica = forms.CharField(label="Institución pública", help_text='', required=False)
	institucion_privada = forms.CharField(label="Institución privada", help_text='', required=False)
	telefono = forms.CharField(label="Teléfono", help_text='', required=False)
	email = forms.EmailField(label="Email", help_text='', required=False)

	class Meta:
		model = Entrevistado

class FrmSeleccion(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	es_candidato = forms.CharField(widget=forms.HiddenInput(), required=False)
	espe_medica = forms.CharField(label="1)Dr. ¿Cuál es su especialidad médica?", help_text='',widget=forms.TextInput(attrs={'readonly':'readonly'}), required=True)
	tiempo_endo = forms.CharField(label="2)Dr. ¿Cuántos años tiene practicando como médico endocrinólogo?", help_text='', required=True)
	cushing_actual_tx = forms.CharField(label="3)Dr. ¿Actualmente cuantos pacientes con Enfermedad de Cushing (No Síndrome de Cushing) tiene en tratamiento?", help_text='', required=True)
	cushing_cm_12m = forms.CharField(label="4)Dr. ¿De los pacientes con Enfermedad de Cushing en tratamiento, cuantos han estado bajo cuidados médicos por 12 meses o más?", help_text='', required=True)
	examen_orina_2 = forms.CharField(label="5)Dr. ¿De los pacientes con Enfermedad de Cushing en tratamiento por 12 meses o más, cuantos han tenido dos o más exámenes de cortisol libre en orina durante el último año?", help_text='', required=True)
	examen_orina_1 = forms.CharField(label="5)Dr. ¿De los pacientes con Enfermedad de Cushing en tratamiento por 12 meses o más, cuantos han tenido un examen de cortisol libre en orina durante el último año?", help_text='', required=True)
	examen_orina_0 = forms.CharField(label="5)Dr. ¿De los pacientes con Enfermedad de Cushing en tratamiento por 12 meses o más, cuantos no han tenido exámenes de cortisol libre en orina durante el último año?.", help_text='', required=True)
	class Meta:
		model = Seleccion

class FrmControl(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	control_alto = forms.CharField(label='Control alto', help_text='', required=True)
	control_bajo = forms.CharField(label='Control bajo', help_text='', required=True)
	control_medio = forms.CharField(label='Control intermedio', help_text='', required=True)
	corti_libre_orina = forms.ChoiceField(label='Cortisol libre en orina', help_text='', required=True, choices=importancia, widget=forms.RadioSelect(attrs={'class':'multi'}))
	hormona_adreno = forms.ChoiceField(label='Hormona adrenocorticotrópica', help_text='', required=True, choices=importancia, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sintomas_paciente = forms.ChoiceField(label='Síntomas del paciente', help_text='', required=True, choices=importancia, widget=forms.RadioSelect(attrs={'class':'multi'}))
	class Meta:
		model = Control

class FrmGenerales(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	edad = forms.CharField(label='2.1.Edad', help_text='', required=True)
	sexo = forms.ChoiceField(label='2.2.Sexo', help_text='', required=True,  choices=sexo, widget=forms.RadioSelect(attrs={'class':'multi'}))
	peso = forms.CharField(label='2.3.Peso', help_text='', required=True)
	talla = forms.CharField(label='2.4.Talla', help_text='', required=True)
	imc = forms.CharField(label='2.5.Índice de masa corporal', help_text='', required=True)
	fecha_diag = forms.DateField(label='2.6.Fecha de diagnóstico de enfermedad de Cushing', help_text='', required=True, widget=forms.TextInput(attrs={'class':'fecha'}))
	fecha_inicio_tx = forms.DateField(label='2.7.Fecha de inicio de tratamiento', help_text='', required=True, widget=forms.TextInput(attrs={'class':'fecha'}))
	fecha_cirugia = forms.DateField(label='2.8.Fecha de cirugia', help_text='', required=True, widget=forms.TextInput(attrs={'class':'fecha'}))
	class Meta:
		model = Generales

class FrmSintomas(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	cara_luna_6 = forms.ChoiceField(label='3.1.1.	Cara de luna (redonda).', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cara_luna_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ojos_jinchados_6 = forms.ChoiceField(label='3.1.2. Ojos hinchados.', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ojos_jinchados_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	tez_purpuras_6 = forms.ChoiceField(label='3.1.3. Tez con marcas púrpuras', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	tez_purpuras_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	acne_6 = forms.ChoiceField(label='3.1.4. Acné severo', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	acne_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	estrias_6 = forms.ChoiceField(label='3.1.5. Estrías', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	estrias_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	moretones_6 = forms.ChoiceField(label='3.1.6.	Moretones y mala cicatrización', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	moretones_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	aumento_abdomen_6 = forms.ChoiceField(label='3.2.1 Aumento de peso en la zona del abdomen', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	aumento_abdomen_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	joroba_6 = forms.ChoiceField(label='3.2.2	Acumulación de grasa en la espalda (joroba)', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	joroba_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	temperatura_baja_6 = forms.ChoiceField(label='3.2.3 Temperatura corporal baja', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	temperatura_baja_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sensibilidad_frio_6 = forms.ChoiceField(label='3.2.4 Sensibilidad al frio', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sensibilidad_frio_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	fatiga_6 = forms.ChoiceField(label='3.2.5	Fatiga severa', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	fatiga_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	osteopenia_6 = forms.ChoiceField(label='3.3.1. Osteopenia.', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	osteopenia_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	osteoporosis_6 = forms.ChoiceField(label='3.3.2. Osteoporosis', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	osteoporosis_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ablan_col_vertebral_6 = forms.ChoiceField(label='3.3.3. Ablandamiento columna vertebral', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ablan_col_vertebral_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	dolores_espalda_6 = forms.ChoiceField(label='3.3.4. Dolores de espalda', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	dolores_espalda_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	fracturas_6 = forms.ChoiceField(label='3.3.5. Fracturas de costillas y vertebras', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	fracturas_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	debilidad_muscular_6 = forms.ChoiceField(label='3.3.6. Debilidad muscular', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	debilidad_muscular_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	debilidad_extrem_6 = forms.ChoiceField(label='3.3.7. Debilidad extremidades inferiores', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	debilidad_extrem_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	hirsutismo_6 = forms.ChoiceField(label='3.4.1. Hirsutismo (crecimiento excesivo de vello)', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	hirsutismo_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ciclo_mesn_6 = forms.ChoiceField(label='3.4.2. Ciclo menstrual irregular', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ciclo_mesn_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	infertilidad_6 = forms.ChoiceField(label='3.5.1. Infertilidad', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	infertilidad_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	disminucion_sexual_6 = forms.ChoiceField(label='3.5.2. Disminución deseo sexual', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	disminucion_sexual_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	impotencia_6 = forms.ChoiceField(label='3.5.3. Impotencia', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	impotencia_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	deficit_cognitivos_6 = forms.ChoiceField(label='3.6.1. Déficits cognitivos', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	deficit_cognitivos_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro1_cual = forms.CharField(label='', help_text='', required=False)
	otro1_6 = forms.ChoiceField(label='3.6.2. Otro ¿Cuál?', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro1_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro2_cual = forms.CharField(label='', help_text='', required=False)
	otro2_6 = forms.ChoiceField(label='3.6.3. Otro ¿Cuál?', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro2_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	class Meta:
		model = Sintomas

class FrmComorbilidades(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)	
	dm1_6 = forms.ChoiceField(label='4.1.1. Diabetes mellitus I', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	dm1_fecha = forms.CharField(label='4.1.1. Diabetes mellitus I', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	dm1_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	dm2_6 = forms.ChoiceField(label='4.1.2. Diabetes mellitus II', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	dm2_fecha = forms.CharField(label='4.1.2. Diabetes mellitus II', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	dm2_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sind_met_6 = forms.ChoiceField(label='4.1.3. Síndrome metabólico', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sind_met_fecha = forms.CharField(label='4.1.3. Síndrome metabólico', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	sind_met_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	int_glucosa_6 = forms.ChoiceField(label='4.1.4. Intolerancia a la glucosa', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	int_glucosa_fecha = forms.CharField(label='4.1.4. Intolerancia a la glucosa', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	int_glucosa_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	obesidad_6 = forms.ChoiceField(label='4.1.5. Obesidad', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	obesidad_fecha = forms.CharField(label='4.1.5. Obesidad', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	obesidad_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	hipertension_6 = forms.ChoiceField(label='4.2.1 Hipertensión', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	hipertension_fecha = forms.CharField(label='4.2.1 Hipertensión', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	hipertension_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	colesterol_6 = forms.ChoiceField(label='4.2.2	Colesterol alto', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	colesterol_fecha = forms.CharField(label='4.2.2	Colesterol alto', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	colesterol_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	trombosis_6 = forms.ChoiceField(label='4.2.3 Trombosis', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	trombosis_fecha = forms.CharField(label='4.2.3 Trombosis', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	trombosis_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	infarto_miocardio_6 = forms.ChoiceField(label='4.2.4 Infarto al miocardio', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	infarto_miocardio_fecha = forms.CharField(label='4.2.4 Infarto al miocardio', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	infarto_miocardio_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	angina_pecho_6 = forms.ChoiceField(label='4.2.5 Angina de pecho', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	angina_pecho_fecha = forms.CharField(label='4.2.5 Angina de pecho', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	angina_pecho_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cardiopatia_6 = forms.ChoiceField(label='4.2.6 Cardiopatía isquémica', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cardiopatia_fecha = forms.CharField(label='4.2.6 Cardiopatía isquémica', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	cardiopatia_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cerebrovascular_6 = forms.ChoiceField(label='4.2.7 Accidente cerebrovascular', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cerebrovascular_fecha = forms.CharField(label='4.2.7 Accidente cerebrovascular', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	cerebrovascular_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	isquemia_6 = forms.ChoiceField(label='4.2.8 Isquemia cerebral transitoria', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	isquemia_fecha = forms.CharField(label='4.2.8 Isquemia cerebral transitoria', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	isquemia_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sepsis_6 = forms.ChoiceField(label='4.3.1. Sepsis', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	sepsis_fecha = forms.CharField(label='4.3.1. Sepsis', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	sepsis_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	neumonia_6 = forms.ChoiceField(label='4.3.2. Neumonía', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	neumonia_fecha = forms.CharField(label='4.3.2. Neumonía', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	neumonia_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	vias_urinarias_6 = forms.ChoiceField(label='4.3.3. Vías urinarias', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	vias_urinarias_fecha = forms.CharField(label='4.3.3. Vías urinarias', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	vias_urinarias_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	pytb_6 = forms.ChoiceField(label='4.3.4. Piel y tejidos blandos', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	pytb_fecha = forms.CharField(label='4.3.4. Piel y tejidos blandos', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	pytb_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	fungicas_6 = forms.ChoiceField(label='4.3.5. Fúngicas', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	fungicas_fecha = forms.CharField(label='4.3.5. Fúngicas', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	fungicas_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	depresion_6 = forms.ChoiceField(label='4.4.1. Depresión', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	depresion_fecha = forms.CharField(label='4.4.1. Depresión', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	depresion_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ansiedad_6 = forms.ChoiceField(label='4.4.2. Ansiedad', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ansiedad_fecha = forms.CharField(label='4.4.2. Ansiedad', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	ansiedad_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	psicosis_6 = forms.ChoiceField(label='4.4.3. Psicosis', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	psicosis_fecha = forms.CharField(label='4.4.3. Psicosis', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	psicosis_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cr_6 = forms.ChoiceField(label='4.5.1. Cálculos renales', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cr_fecha = forms.CharField(label='4.5.1. Cálculos renales', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	cr_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro1_cual = forms.CharField(label='', help_text='', required=False)
	otro1_6 = forms.ChoiceField(label='4.5.2. Otro 1 ¿Cuál?', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro1_fecha = forms.CharField(label='4.5.2. Otro 1 ¿Cuál?', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	otro1_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro2_cual = forms.CharField(label='', help_text='', required=False)
	otro2_6 = forms.ChoiceField(label='4.5.3. Otro 2 ¿Cuál?', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	otro2_fecha = forms.CharField(label='4.5.3. Otro 2 ¿Cuál?', help_text='', required=False, widget=forms.TextInput(attrs={'class':'fecha'}))
	otro2_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	class Meta:
		model = Comorbilidades


class FrmEspecialista(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	endo_1_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_2_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_3_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_4_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_5_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_6_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_7_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_8_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_9_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_10_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_11_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	endo_12_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_1_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_2_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_3_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_4_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_5_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_6_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_7_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_8_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_9_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_10_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_11_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	inter_12_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_1_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_2_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_3_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_4_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_5_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_6_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_7_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_8_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_9_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_10_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_11_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	cx_12_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_1_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_2_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_3_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_4_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_5_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_6_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_7_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_8_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_9_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_10_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_11_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	urg_12_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_cual = forms.CharField(label='', help_text='', required=False)
	otro1_1_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_2_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_3_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_4_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_5_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_6_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_7_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_8_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_9_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_10_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_11_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro1_12_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_cual = forms.CharField(label='', help_text='', required=False)
	otro2_1_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_2_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_3_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_4_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_5_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_6_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_7_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_8_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_9_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_10_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_11_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	otro2_12_mes = forms.ChoiceField(label='', help_text='', required=False,choices=OpcionesNumericas())
	class Meta:
		model = Especialista


class FrmHospitalizacion(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	hosp_1_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_2_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_3_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_4_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_5_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_6_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_7_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_8_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_9_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_10_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_11_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	hosp_12_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_1_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_2_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_3_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_4_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_5_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_6_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_7_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_8_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_9_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_10_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_11_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	ci_12_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes())
	class Meta:
		model = Hospitalizacion

class FrmLaboratorio(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	lab = forms.CharField(widget=forms.HiddenInput(), required=False)
	clo_no_1_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_2_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_3_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_4_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_5_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_6_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_7_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_8_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_9_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_10_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_11_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	clo_no_12_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_1_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_2_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_3_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_4_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_5_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_6_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_7_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_8_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_9_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_10_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_11_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	ha_no_12_mes = forms.ChoiceField(label='', help_text='', required=False, choices=DiasMes(), widget=forms.Select(attrs={'class':'lab'}))
	control_1_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_2_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_3_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_4_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_5_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_6_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_7_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_8_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_9_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_10_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_11_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	control_12_mes = forms.ChoiceField(label='', help_text='', required=False, choices=ce)
	psd_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	psd_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	psd_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	psd_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	acth_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	acth_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	acth_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	acth_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	metirapona_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	metirapona_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	metirapona_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	metirapona_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	crh_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	crh_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	crh_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	crh_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	seno_petroso_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	seno_petroso_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	seno_petroso_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	seno_petroso_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	tomografia_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	tomografia_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	tomografia_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	tomografia_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	res_magnetica_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	res_magnetica_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	res_magnetica_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	res_magnetica_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	otro1_cual = forms.CharField(label='', help_text='', required=False)
	otro1_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	otro1_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	otro1_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	otro1_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	otro2_cual = forms.CharField(label='', help_text='', required=False)
	otro2_si_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	otro2_pruebas_6 = forms.CharField(label='', help_text='', required=False)
	otro2_si_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi_lab'}))
	otro2_pruebas_12 = forms.CharField(label='', help_text='', required=False)
	class Meta:
		model = Laboratorio


class FrmIntervenciones(ModelForm):
	"""Formulario de enrtevistado"""
	# 6 meses
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	rx_si_6 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	rx_veces_6 = forms.CharField(label='', help_text='', required=False)
	rx_hipo_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	rx_cerebro_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	rx_otras_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_si_6 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	radiocirugia_veces_6 = forms.CharField(label='', help_text='', required=False)
	radiocirugia_hipo_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_visual_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_craneal_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_otras_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_si_6 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cirugia_veces_6 = forms.CharField(label='', help_text='', required=False)
	cirugia_hormo_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_diabetes_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_cerebro_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_visual_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_menin_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_cefalo_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_otras_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	adrena_si_6 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	adrena_veces_6 = forms.CharField(label='', help_text='', required=False)
	adrena_nelson_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	adrena_otras_comp_6 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	#12 meses
	rx_si_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	rx_veces_12 = forms.CharField(label='', help_text='', required=False)
	rx_hipo_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	rx_cerebro_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	rx_otras_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_si_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	radiocirugia_veces_12 = forms.CharField(label='', help_text='', required=False)
	radiocirugia_hipo_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_visual_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_craneal_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	radiocirugia_otras_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_si_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	cirugia_veces_12 = forms.CharField(label='', help_text='', required=False)
	cirugia_hormo_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_diabetes_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_cerebro_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_visual_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_menin_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_cefalo_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	cirugia_otras_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	adrena_si_12 = forms.ChoiceField(label='', help_text='', required=True, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	adrena_veces_12 = forms.CharField(label='', help_text='', required=False)
	adrena_nelson_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	adrena_otras_comp_12 = forms.BooleanField(label='', help_text='', required=False, widget=forms.CheckboxInput())
	
	class Meta:
		model = Intervenciones


class FrmTratamiento(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	tx = forms.CharField(widget=forms.HiddenInput(), required=False)
	ec_keto_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_keto_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_caber_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_caber_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_mife_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_mife_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_otro1_cual = forms.CharField(label='', help_text='', required=False)
	ec_otro1_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_otro1_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_otro2_cual = forms.CharField(label='', help_text='', required=False)
	ec_otro2_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_otro2_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_otro3_cual = forms.CharField(label='', help_text='', required=False)
	ec_otro3_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	ec_otro3_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_metfo_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_metfo_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_sulfo_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_sulfo_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_tiazo_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_tiazo_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_dpp4_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_dpp4_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_glp1_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_glp1_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_insu_rapida_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_insu_rapida_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_insu_lenta_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	diab_insu_lenta_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_ieca_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_ieca_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_bra_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_bra_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_beta_bloq_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_beta_bloq_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_fibratos_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_fibratos_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_bcc_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_bcc_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_diuretico_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_diuretico_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_iac_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_iac_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_vit_b3_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_vit_b3_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_nitrato_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_nitrato_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_antiplaq_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_antiplaq_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_acido_acetil_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_acido_acetil_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_estatina_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_estatina_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_sab_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	car_sab_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_sepsis_cual = forms.CharField(label='', help_text='', required=False)
	inf_sepsis_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_sepsis_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_neumonia_cual = forms.CharField(label='', help_text='', required=False)
	inf_neumonia_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_neumonia_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_vias_cual = forms.CharField(label='', help_text='', required=False)
	inf_vias_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_vias_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_ptb_cual = forms.CharField(label='', help_text='', required=False)
	inf_ptb_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_ptb_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_fungi_cual = forms.CharField(label='', help_text='', required=False)
	inf_fungi_6 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	inf_fungi_12 = forms.ChoiceField(label='', help_text='', required=False, choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}))
	class Meta:
		model = Tratamiento

class FrmComorbilidadesTx(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	tx = forms.CharField(widget=forms.HiddenInput(), required=False)
	ment_depre_cual = forms.CharField(label='', help_text='', required=False)
	ment_depre_6 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ment_depre_12 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ment_ansi_cual = forms.CharField(label='', help_text='', required=False)
	ment_ansi_6 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ment_ansi_12 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ment_psico_cual = forms.CharField(label='', help_text='', required=False)
	ment_psico_6 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ment_psico_12 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ot_cr_cual = forms.CharField(label='', help_text='', required=False)
	ot_cr_6 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ot_cr_12 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ot_otra1_cual = forms.CharField(label='', help_text='', required=False)
	ot_otra1_6 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ot_otra1_12 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ot_otra2_cual = forms.CharField(label='', help_text='', required=False)
	ot_otra2_6 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	ot_otra2_12 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	class Meta:
		model = ComorbilidadesTx


class FrmComplicaciones(ModelForm):
	"""Formulario de enrtevistado"""
	folio = forms.CharField(widget=forms.HiddenInput(), required=False)
	cual_1 = forms.CharField(label='', help_text='', required=False)
	hosp_si_1 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	hosp_eventos_1 = forms.CharField(label='', help_text='', required=False)
	hosp_duracion_1 = forms.CharField(label='', help_text='', required=False)
	espe_si_1 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	espe_eventos_1 = forms.CharField(label='', help_text='', required=False)
	espe_duracion_1 = forms.CharField(label='', help_text='', required=False)
	otras_visitas_cual_1 = forms.CharField(label='', help_text='', required=False)
	otras_visitas_si_1 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	otras_visitas_eventos_1 = forms.CharField(label='', help_text='', required=False)
	otras_visitas_duracion_1 = forms.CharField(label='', help_text='', required=False)
	proc_1 = forms.CharField(label='', help_text='', required=False)
	proc_si_1 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	proc_eventos_1 = forms.CharField(label='', help_text='', required=False)
	proc_duracion_1 = forms.CharField(label='', help_text='', required=False)
	tx_1 = forms.CharField(label='', help_text='', required=False)
	tx_posologia_1 = forms.CharField(label='', help_text='', required=False)
	tx_si_1 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	tx_eventos_1 = forms.CharField(label='', help_text='', required=False)
	tx_duracion_1 = forms.CharField(label='', help_text='', required=False)
	cual_2 = forms.CharField(label='', help_text='', required=False)
	hosp_si_2 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	hosp_eventos_2 = forms.CharField(label='', help_text='', required=False)
	hosp_duracion_2 = forms.CharField(label='', help_text='', required=False)
	espe_si_2 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	espe_eventos_2 = forms.CharField(label='', help_text='', required=False)
	espe_duracion_2 = forms.CharField(label='', help_text='', required=False)
	otras_visitas_cual_2 = forms.CharField(label='', help_text='', required=False)
	otras_visitas_si_2 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	otras_visitas_eventos_2 = forms.CharField(label='', help_text='', required=False)
	otras_visitas_duracion_2 = forms.CharField(label='', help_text='', required=False)
	proc_2 = forms.CharField(label='', help_text='', required=False)
	proc_si_2 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	proc_eventos_2 = forms.CharField(label='', help_text='', required=False)
	proc_duracion_2 = forms.CharField(label='', help_text='', required=False)
	tx_2 = forms.CharField(label='', help_text='', required=False)
	tx_posologia_2 = forms.CharField(label='', help_text='', required=False)
	tx_si_2 = forms.ChoiceField(label='', help_text='', choices=sino, widget=forms.RadioSelect(attrs={'class':'multi'}), required=False)
	tx_eventos_2 = forms.CharField(label='', help_text='', required=False)
	tx_duracion_2 = forms.CharField(label='', help_text='', required=False)
	class Meta:
		model = Complicaciones