#encoding:utf-8

from django.db import models

# Create your models here.

class RegEnt(models.Model):
    usuario = models.TextField(blank=True) # This field type is a guess.
    fecha_registro = models.TextField(blank=True) # This field type is a guess.
    hora_registro = models.TextField(blank=True) # This field type is a guess.
    tipo_registro = models.TextField(blank=True) # This field type is a guess.
    ip = models.TextField(blank=True) # This field type is a guess.
    class Meta:
        db_table = 'registro'

class Entrevistado(models.Model):
	"""Datos del Entrevistado"""
	folio_principal = models.CharField(max_length=150)
	monitor_clinico = models.CharField(max_length=150, blank=True, null=True)
	supervisor = models.CharField(max_length=150, blank=True, null=True)
	fecha_llenado = models.CharField(max_length=150, blank=True)
	nombre_medico = models.CharField(max_length=150, blank=True)
	especialidad = models.CharField(max_length=150, blank=True)
	pais = models.CharField(max_length=150, blank=True)
	institucion_publica = models.CharField(max_length=150, blank=True)
	institucion_privada = models.CharField(max_length=150, blank=True)
	telefono = models.CharField(max_length=150, blank=True)
	email = models.CharField(max_length=150, blank=True)
	hora_guardado = models.DateTimeField(auto_now=True)
	class Meta:
		db_table = 'entrevistado'
		
class Seleccion(models.Model):
	"""Datos del Seleccion"""
	folio = models.CharField(max_length=150)
	espe_medica = models.CharField(max_length=150)
	tiempo_endo = models.CharField(max_length=150)
	cushing_actual_tx = models.CharField(max_length=150)
	cushing_cm_12m = models.CharField(max_length=150)
	examen_orina_2 = models.CharField(max_length=150)
	examen_orina_1 = models.CharField(max_length=150)
	examen_orina_0 = models.CharField(max_length=150)
	es_candidato = models.CharField(max_length=150, blank=True, null=True)
	hora_guardado = models.DateTimeField(auto_now=True)
	class Meta:
		db_table = 'seleccion'

class Control(models.Model):
	"""Datos del Control"""
	folio = models.CharField(max_length=150)
	control_alto = models.CharField(max_length=150)
	control_bajo = models.CharField(max_length=150)
	control_medio = models.CharField(max_length=150)
	corti_libre_orina = models.CharField(max_length=150)
	hormona_adreno = models.CharField(max_length=150)
	sintomas_paciente = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)
	class Meta:
		db_table = 'control'

class Generales(models.Model):
	"""Datos del Generales"""
	folio = models.CharField(max_length=150)
	edad = models.CharField(max_length=150)
	sexo = models.CharField(max_length=150)
	peso = models.CharField(max_length=150)
	talla = models.CharField(max_length=150)
	imc = models.CharField(max_length=150)
	fecha_diag = models.DateField(auto_now=False)
	fecha_inicio_tx = models.DateField(auto_now=False)
	fecha_cirugia = models.DateField(auto_now=False)
	hora_guardado = models.DateTimeField(auto_now=True)
	class Meta:
		db_table = 'generales'

# Por generar en el excel


class Sintomas(models.Model):
	"""Datos del Sintomas"""
	folio = models.CharField(max_length=150)
	cara_luna_6 = models.CharField(max_length=150)
	cara_luna_12 = models.CharField(max_length=150)
	ojos_jinchados_6 = models.CharField(max_length=150)
	ojos_jinchados_12 = models.CharField(max_length=150)
	tez_purpuras_6 = models.CharField(max_length=150)
	tez_purpuras_12 = models.CharField(max_length=150)
	acne_6 = models.CharField(max_length=150)
	acne_12 = models.CharField(max_length=150)
	estrias_6 = models.CharField(max_length=150)
	estrias_12 = models.CharField(max_length=150)
	moretones_6 = models.CharField(max_length=150)
	moretones_12 = models.CharField(max_length=150)
	aumento_abdomen_6 = models.CharField(max_length=150)
	aumento_abdomen_12 = models.CharField(max_length=150)
	joroba_6 = models.CharField(max_length=150)
	joroba_12 = models.CharField(max_length=150)
	temperatura_baja_6 = models.CharField(max_length=150)
	temperatura_baja_12 = models.CharField(max_length=150)
	sensibilidad_frio_6 = models.CharField(max_length=150)
	sensibilidad_frio_12 = models.CharField(max_length=150)
	fatiga_6 = models.CharField(max_length=150)
	fatiga_12 = models.CharField(max_length=150)
	osteopenia_6 = models.CharField(max_length=150)
	osteopenia_12 = models.CharField(max_length=150)
	osteoporosis_6 = models.CharField(max_length=150)
	osteoporosis_12 = models.CharField(max_length=150)
	ablan_col_vertebral_6 = models.CharField(max_length=150)
	ablan_col_vertebral_12 = models.CharField(max_length=150)
	dolores_espalda_6 = models.CharField(max_length=150)
	dolores_espalda_12 = models.CharField(max_length=150)
	fracturas_6 = models.CharField(max_length=150)
	fracturas_12 = models.CharField(max_length=150)
	debilidad_muscular_6 = models.CharField(max_length=150)
	debilidad_muscular_12 = models.CharField(max_length=150)
	debilidad_extrem_6 = models.CharField(max_length=150)
	debilidad_extrem_12 = models.CharField(max_length=150)
	hirsutismo_6 = models.CharField(max_length=150)
	hirsutismo_12 = models.CharField(max_length=150)
	ciclo_mesn_6 = models.CharField(max_length=150)
	ciclo_mesn_12 = models.CharField(max_length=150)
	infertilidad_6 = models.CharField(max_length=150)
	infertilidad_12 = models.CharField(max_length=150)
	disminucion_sexual_6 = models.CharField(max_length=150)
	disminucion_sexual_12 = models.CharField(max_length=150)
	impotencia_6 = models.CharField(max_length=150)
	impotencia_12 = models.CharField(max_length=150)
	deficit_cognitivos_6 = models.CharField(max_length=150)
	deficit_cognitivos_12 = models.CharField(max_length=150)
	otro1_cual = models.CharField(max_length=150)
	otro1_6 = models.CharField(max_length=150)
	otro1_12 = models.CharField(max_length=150)
	otro2_cual = models.CharField(max_length=150)
	otro2_6 = models.CharField(max_length=150)
	otro2_12 = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'sintomas'

class Comorbilidades(models.Model):
	"""Datos del Generales"""
	folio = models.CharField(max_length=150)
	dm1_fecha = models.CharField(max_length=150)
	dm1_6 = models.CharField(max_length=150)
	dm1_12 = models.CharField(max_length=150)
	dm2_fecha = models.CharField(max_length=150)
	dm2_6 = models.CharField(max_length=150)
	dm2_12 = models.CharField(max_length=150)
	sind_met_fecha = models.CharField(max_length=150)
	sind_met_6 = models.CharField(max_length=150)
	sind_met_12 = models.CharField(max_length=150)
	int_glucosa_fecha = models.CharField(max_length=150)
	int_glucosa_6 = models.CharField(max_length=150)
	int_glucosa_12 = models.CharField(max_length=150)
	obesidad_fecha = models.CharField(max_length=150)
	obesidad_6 = models.CharField(max_length=150)
	obesidad_12 = models.CharField(max_length=150)
	hipertension_fecha = models.CharField(max_length=150)
	hipertension_6 = models.CharField(max_length=150)
	hipertension_12 = models.CharField(max_length=150)
	colesterol_fecha = models.CharField(max_length=150)
	colesterol_6 = models.CharField(max_length=150)
	colesterol_12 = models.CharField(max_length=150)
	trombosis_fecha = models.CharField(max_length=150)
	trombosis_6 = models.CharField(max_length=150)
	trombosis_12 = models.CharField(max_length=150)
	infarto_miocardio_fecha = models.CharField(max_length=150)
	infarto_miocardio_6 = models.CharField(max_length=150)
	infarto_miocardio_12 = models.CharField(max_length=150)
	angina_pecho_fecha = models.CharField(max_length=150)
	angina_pecho_6 = models.CharField(max_length=150)
	angina_pecho_12 = models.CharField(max_length=150)
	cardiopatia_fecha = models.CharField(max_length=150)
	cardiopatia_6 = models.CharField(max_length=150)
	cardiopatia_12 = models.CharField(max_length=150)
	cerebrovascular_fecha = models.CharField(max_length=150)
	cerebrovascular_6 = models.CharField(max_length=150)
	cerebrovascular_12 = models.CharField(max_length=150)
	isquemia_fecha = models.CharField(max_length=150)
	isquemia_6 = models.CharField(max_length=150)
	isquemia_12 = models.CharField(max_length=150)
	sepsis_fecha = models.CharField(max_length=150)
	sepsis_6 = models.CharField(max_length=150)
	sepsis_12 = models.CharField(max_length=150)
	neumonia_fecha = models.CharField(max_length=150)
	neumonia_6 = models.CharField(max_length=150)
	neumonia_12 = models.CharField(max_length=150)
	vias_urinarias_fecha = models.CharField(max_length=150)
	vias_urinarias_6 = models.CharField(max_length=150)
	vias_urinarias_12 = models.CharField(max_length=150)
	pytb_fecha = models.CharField(max_length=150)
	pytb_6 = models.CharField(max_length=150)
	pytb_12 = models.CharField(max_length=150)
	fungicas_fecha = models.CharField(max_length=150)
	fungicas_6 = models.CharField(max_length=150)
	fungicas_12 = models.CharField(max_length=150)
	depresion_fecha = models.CharField(max_length=150)
	depresion_6 = models.CharField(max_length=150)
	depresion_12 = models.CharField(max_length=150)
	ansiedad_fecha = models.CharField(max_length=150)
	ansiedad_6 = models.CharField(max_length=150)
	ansiedad_12 = models.CharField(max_length=150)
	psicosis_fecha = models.CharField(max_length=150)
	psicosis_6 = models.CharField(max_length=150)
	psicosis_12 = models.CharField(max_length=150)
	cr_fecha = models.CharField(max_length=150)
	cr_6 = models.CharField(max_length=150)
	cr_12 = models.CharField(max_length=150)
	otro1_cual = models.CharField(max_length=150)
	otro1_fecha = models.CharField(max_length=150)
	otro1_6 = models.CharField(max_length=150)
	otro1_12 = models.CharField(max_length=150)
	otro2_cual = models.CharField(max_length=150)
	otro2_fecha = models.CharField(max_length=150)
	otro2_6 = models.CharField(max_length=150)
	otro2_12 = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'comorbilidades'

class Especialista(models.Model):
	"""Datos del Especialista"""
	folio = models.CharField(max_length=150)
	endo_1_mes = models.CharField(max_length=150)
	endo_2_mes = models.CharField(max_length=150)
	endo_3_mes = models.CharField(max_length=150)
	endo_4_mes = models.CharField(max_length=150)
	endo_5_mes = models.CharField(max_length=150)
	endo_6_mes = models.CharField(max_length=150)
	endo_7_mes = models.CharField(max_length=150)
	endo_8_mes = models.CharField(max_length=150)
	endo_9_mes = models.CharField(max_length=150)
	endo_10_mes = models.CharField(max_length=150)
	endo_11_mes = models.CharField(max_length=150)
	endo_12_mes = models.CharField(max_length=150)
	inter_1_mes = models.CharField(max_length=150)
	inter_2_mes = models.CharField(max_length=150)
	inter_3_mes = models.CharField(max_length=150)
	inter_4_mes = models.CharField(max_length=150)
	inter_5_mes = models.CharField(max_length=150)
	inter_6_mes = models.CharField(max_length=150)
	inter_7_mes = models.CharField(max_length=150)
	inter_8_mes = models.CharField(max_length=150)
	inter_9_mes = models.CharField(max_length=150)
	inter_10_mes = models.CharField(max_length=150)
	inter_11_mes = models.CharField(max_length=150)
	inter_12_mes = models.CharField(max_length=150)
	cx_1_mes = models.CharField(max_length=150)
	cx_2_mes = models.CharField(max_length=150)
	cx_3_mes = models.CharField(max_length=150)
	cx_4_mes = models.CharField(max_length=150)
	cx_5_mes = models.CharField(max_length=150)
	cx_6_mes = models.CharField(max_length=150)
	cx_7_mes = models.CharField(max_length=150)
	cx_8_mes = models.CharField(max_length=150)
	cx_9_mes = models.CharField(max_length=150)
	cx_10_mes = models.CharField(max_length=150)
	cx_11_mes = models.CharField(max_length=150)
	cx_12_mes = models.CharField(max_length=150)
	urg_1_mes = models.CharField(max_length=150)
	urg_2_mes = models.CharField(max_length=150)
	urg_3_mes = models.CharField(max_length=150)
	urg_4_mes = models.CharField(max_length=150)
	urg_5_mes = models.CharField(max_length=150)
	urg_6_mes = models.CharField(max_length=150)
	urg_7_mes = models.CharField(max_length=150)
	urg_8_mes = models.CharField(max_length=150)
	urg_9_mes = models.CharField(max_length=150)
	urg_10_mes = models.CharField(max_length=150)
	urg_11_mes = models.CharField(max_length=150)
	urg_12_mes = models.CharField(max_length=150)
	otro1_cual = models.CharField(max_length=150)
	otro1_1_mes = models.CharField(max_length=150)
	otro1_2_mes = models.CharField(max_length=150)
	otro1_3_mes = models.CharField(max_length=150)
	otro1_4_mes = models.CharField(max_length=150)
	otro1_5_mes = models.CharField(max_length=150)
	otro1_6_mes = models.CharField(max_length=150)
	otro1_7_mes = models.CharField(max_length=150)
	otro1_8_mes = models.CharField(max_length=150)
	otro1_9_mes = models.CharField(max_length=150)
	otro1_10_mes = models.CharField(max_length=150)
	otro1_11_mes = models.CharField(max_length=150)
	otro1_12_mes = models.CharField(max_length=150)
	otro2_cual = models.CharField(max_length=150)
	otro2_1_mes = models.CharField(max_length=150)
	otro2_2_mes = models.CharField(max_length=150)
	otro2_3_mes = models.CharField(max_length=150)
	otro2_4_mes = models.CharField(max_length=150)
	otro2_5_mes = models.CharField(max_length=150)
	otro2_6_mes = models.CharField(max_length=150)
	otro2_7_mes = models.CharField(max_length=150)
	otro2_8_mes = models.CharField(max_length=150)
	otro2_9_mes = models.CharField(max_length=150)
	otro2_10_mes = models.CharField(max_length=150)
	otro2_11_mes = models.CharField(max_length=150)
	otro2_12_mes = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)
	class Meta:
		db_table = 'especialista'

class Hospitalizacion(models.Model):
	"""Datos del Hospitalizacion"""
	folio = models.CharField(max_length=150)
	hosp_1_mes = models.CharField(max_length=150)
	hosp_2_mes = models.CharField(max_length=150)
	hosp_3_mes = models.CharField(max_length=150)
	hosp_4_mes = models.CharField(max_length=150)
	hosp_5_mes = models.CharField(max_length=150)
	hosp_6_mes = models.CharField(max_length=150)
	hosp_7_mes = models.CharField(max_length=150)
	hosp_8_mes = models.CharField(max_length=150)
	hosp_9_mes = models.CharField(max_length=150)
	hosp_10_mes = models.CharField(max_length=150)
	hosp_11_mes = models.CharField(max_length=150)
	hosp_12_mes = models.CharField(max_length=150)
	ci_1_mes = models.CharField(max_length=150)
	ci_2_mes = models.CharField(max_length=150)
	ci_3_mes = models.CharField(max_length=150)
	ci_4_mes = models.CharField(max_length=150)
	ci_5_mes = models.CharField(max_length=150)
	ci_6_mes = models.CharField(max_length=150)
	ci_7_mes = models.CharField(max_length=150)
	ci_8_mes = models.CharField(max_length=150)
	ci_9_mes = models.CharField(max_length=150)
	ci_10_mes = models.CharField(max_length=150)
	ci_11_mes = models.CharField(max_length=150)
	ci_12_mes = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'hospitalizacion'

class Laboratorio(models.Model):
	"""Datos del Laboratorio"""
	folio = models.CharField(max_length=150)
	clo_no_1_mes = models.CharField(max_length=150)
	clo_no_2_mes = models.CharField(max_length=150)
	clo_no_3_mes = models.CharField(max_length=150)
	clo_no_4_mes = models.CharField(max_length=150)
	clo_no_5_mes = models.CharField(max_length=150)
	clo_no_6_mes = models.CharField(max_length=150)
	clo_no_7_mes = models.CharField(max_length=150)
	clo_no_8_mes = models.CharField(max_length=150)
	clo_no_9_mes = models.CharField(max_length=150)
	clo_no_10_mes = models.CharField(max_length=150)
	clo_no_11_mes = models.CharField(max_length=150)
	clo_no_12_mes = models.CharField(max_length=150)
	ha_no_1_mes = models.CharField(max_length=150)
	ha_no_2_mes = models.CharField(max_length=150)
	ha_no_3_mes = models.CharField(max_length=150)
	ha_no_4_mes = models.CharField(max_length=150)
	ha_no_5_mes = models.CharField(max_length=150)
	ha_no_6_mes = models.CharField(max_length=150)
	ha_no_7_mes = models.CharField(max_length=150)
	ha_no_8_mes = models.CharField(max_length=150)
	ha_no_9_mes = models.CharField(max_length=150)
	ha_no_10_mes = models.CharField(max_length=150)
	ha_no_11_mes = models.CharField(max_length=150)
	ha_no_12_mes = models.CharField(max_length=150)
	lab = models.TextField()
	# Columnas no contabilizadas en el excel
	control_1_mes = models.CharField(max_length=150)
	control_2_mes = models.CharField(max_length=150)
	control_3_mes = models.CharField(max_length=150)
	control_4_mes = models.CharField(max_length=150)
	control_5_mes = models.CharField(max_length=150)
	control_6_mes = models.CharField(max_length=150)
	control_7_mes = models.CharField(max_length=150)
	control_8_mes = models.CharField(max_length=150)
	control_9_mes = models.CharField(max_length=150)
	control_10_mes = models.CharField(max_length=150)
	control_11_mes = models.CharField(max_length=150)
	control_12_mes = models.CharField(max_length=150)
	# Terminan las columnas no coontabilizadas en excel
	psd_si_6 = models.CharField(max_length=150)
	psd_pruebas_6 = models.CharField(max_length=150)
	psd_si_12 = models.CharField(max_length=150)
	psd_pruebas_12 = models.CharField(max_length=150)
	acth_si_6 = models.CharField(max_length=150)
	acth_pruebas_6 = models.CharField(max_length=150)
	acth_si_12 = models.CharField(max_length=150)
	acth_pruebas_12 = models.CharField(max_length=150)
	metirapona_si_6 = models.CharField(max_length=150)
	metirapona_pruebas_6 = models.CharField(max_length=150)
	metirapona_si_12 = models.CharField(max_length=150)
	metirapona_pruebas_12 = models.CharField(max_length=150)
	crh_si_6 = models.CharField(max_length=150)
	crh_pruebas_6 = models.CharField(max_length=150)
	crh_si_12 = models.CharField(max_length=150)
	crh_pruebas_12 = models.CharField(max_length=150)
	seno_petroso_si_6 = models.CharField(max_length=150)
	seno_petroso_pruebas_6 = models.CharField(max_length=150)
	seno_petroso_si_12 = models.CharField(max_length=150)
	seno_petroso_pruebas_12 = models.CharField(max_length=150)
	tomografia_si_6 = models.CharField(max_length=150)
	tomografia_pruebas_6 = models.CharField(max_length=150)
	tomografia_si_12 = models.CharField(max_length=150)
	tomografia_pruebas_12 = models.CharField(max_length=150)
	res_magnetica_si_6 = models.CharField(max_length=150)
	res_magnetica_pruebas_6 = models.CharField(max_length=150)
	res_magnetica_si_12 = models.CharField(max_length=150)
	res_magnetica_pruebas_12 = models.CharField(max_length=150)
	otro1_cual = models.CharField(max_length=150)
	otro1_si_6 = models.CharField(max_length=150)
	otro1_pruebas_6 = models.CharField(max_length=150)
	otro1_si_12 = models.CharField(max_length=150)
	otro1_pruebas_12 = models.CharField(max_length=150)
	otro2_cual = models.CharField(max_length=150)
	otro2_si_6 = models.CharField(max_length=150)
	otro2_pruebas_6 = models.CharField(max_length=150)
	otro2_si_12 = models.CharField(max_length=150)
	otro2_pruebas_12 = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'laboratorio'

class Intervenciones(models.Model):
	"""Datos del Intervenciones"""
	# 6 meses
	folio = models.CharField(max_length=150)
	rx_si_6 = models.CharField(max_length=150)
	rx_veces_6 = models.CharField(max_length=150)
	rx_hipo_comp_6 = models.CharField(max_length=150)
	rx_cerebro_comp_6 = models.CharField(max_length=150)
	rx_otras_comp_6 = models.CharField(max_length=150)
	radiocirugia_si_6 = models.CharField(max_length=150)
	radiocirugia_veces_6 = models.CharField(max_length=150)
	radiocirugia_hipo_comp_6 = models.CharField(max_length=150)
	radiocirugia_visual_comp_6 = models.CharField(max_length=150)
	radiocirugia_craneal_comp_6 = models.CharField(max_length=150)
	radiocirugia_otras_comp_6 = models.CharField(max_length=150)
	cirugia_si_6 = models.CharField(max_length=150)
	cirugia_veces_6 = models.CharField(max_length=150)
	cirugia_hormo_comp_6 = models.CharField(max_length=150)
	cirugia_diabetes_comp_6 = models.CharField(max_length=150)
	cirugia_cerebro_comp_6 = models.CharField(max_length=150)
	cirugia_visual_comp_6 = models.CharField(max_length=150)
	cirugia_menin_comp_6 = models.CharField(max_length=150)
	cirugia_cefalo_comp_6 = models.CharField(max_length=150)
	cirugia_otras_comp_6 = models.CharField(max_length=150)
	adrena_si_6 = models.CharField(max_length=150)
	adrena_veces_6 = models.CharField(max_length=150)
	adrena_nelson_comp_6 = models.CharField(max_length=150)
	adrena_otras_comp_6 = models.CharField(max_length=150)
	# 12 mese
	rx_si_12 = models.CharField(max_length=150)
	rx_veces_12 = models.CharField(max_length=150)
	rx_hipo_comp_12 = models.CharField(max_length=150)
	rx_cerebro_comp_12 = models.CharField(max_length=150)
	rx_otras_comp_12 = models.CharField(max_length=150)
	radiocirugia_si_12 = models.CharField(max_length=150)
	radiocirugia_veces_12 = models.CharField(max_length=150)
	radiocirugia_hipo_comp_12 = models.CharField(max_length=150)
	radiocirugia_visual_comp_12 = models.CharField(max_length=150)
	radiocirugia_craneal_comp_12 = models.CharField(max_length=150)
	radiocirugia_otras_comp_12 = models.CharField(max_length=150)
	cirugia_si_12 = models.CharField(max_length=150)
	cirugia_veces_12 = models.CharField(max_length=150)
	cirugia_hormo_comp_12 = models.CharField(max_length=150)
	cirugia_diabetes_comp_12 = models.CharField(max_length=150)
	cirugia_cerebro_comp_12 = models.CharField(max_length=150)
	cirugia_visual_comp_12 = models.CharField(max_length=150)
	cirugia_menin_comp_12 = models.CharField(max_length=150)
	cirugia_cefalo_comp_12 = models.CharField(max_length=150)
	cirugia_otras_comp_12 = models.CharField(max_length=150)
	adrena_si_12 = models.CharField(max_length=150)
	adrena_veces_12 = models.CharField(max_length=150)
	adrena_nelson_comp_12 = models.CharField(max_length=150)
	adrena_otras_comp_12 = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'intervenciones'

class Tratamiento(models.Model):
	"""Datos del Tratamiento"""
	folio = models.CharField(max_length=150, blank=True)
	ec_keto_6 = models.CharField(max_length=150, blank=True)
	ec_keto_12 = models.CharField(max_length=150, blank=True)
	ec_caber_6 = models.CharField(max_length=150, blank=True)
	ec_caber_12 = models.CharField(max_length=150, blank=True)
	ec_mife_6 = models.CharField(max_length=150, blank=True)
	ec_mife_12 = models.CharField(max_length=150, blank=True)
	ec_otro1_cuantos = models.CharField(max_length=150, blank=True)
	ec_otro1_6 = models.CharField(max_length=150, blank=True)
	ec_otro1_12 = models.CharField(max_length=150, blank=True)
	ec_otro2_cuantos = models.CharField(max_length=150, blank=True)
	ec_otro2_6 = models.CharField(max_length=150, blank=True)
	ec_otro2_12 = models.CharField(max_length=150, blank=True)
	ec_otro3_cuantos = models.CharField(max_length=150, blank=True)
	ec_otro3_6 = models.CharField(max_length=150, blank=True)
	ec_otro3_12 = models.CharField(max_length=150, blank=True)
	diab_metfo_6 = models.CharField(max_length=150, blank=True)
	diab_metfo_12 = models.CharField(max_length=150, blank=True)
	diab_sulfo_6 = models.CharField(max_length=150, blank=True)
	diab_sulfo_12 = models.CharField(max_length=150, blank=True)
	diab_tiazo_6 = models.CharField(max_length=150, blank=True)
	diab_tiazo_12 = models.CharField(max_length=150, blank=True)
	diab_dpp4_6 = models.CharField(max_length=150, blank=True)
	diab_dpp4_12 = models.CharField(max_length=150, blank=True)
	diab_glp1_6 = models.CharField(max_length=150, blank=True)
	diab_glp1_12 = models.CharField(max_length=150, blank=True)
	diab_insu_rapida_6 = models.CharField(max_length=150, blank=True)
	diab_insu_rapida_12 = models.CharField(max_length=150, blank=True)
	diab_insu_lenta_6 = models.CharField(max_length=150, blank=True)
	diab_insu_lenta_12 = models.CharField(max_length=150, blank=True)
	car_ieca_6 = models.CharField(max_length=150, blank=True)
	car_ieca_12 = models.CharField(max_length=150, blank=True)
	car_bra_6 = models.CharField(max_length=150, blank=True)
	car_bra_12 = models.CharField(max_length=150, blank=True)
	car_beta_bloq_6 = models.CharField(max_length=150, blank=True)
	car_beta_bloq_12 = models.CharField(max_length=150, blank=True)
	car_fibratos_6 = models.CharField(max_length=150, blank=True)
	car_fibratos_12 = models.CharField(max_length=150, blank=True)
	car_bcc_6 = models.CharField(max_length=150, blank=True)
	car_bcc_12 = models.CharField(max_length=150, blank=True)
	car_diuretico_6 = models.CharField(max_length=150, blank=True)
	car_diuretico_12 = models.CharField(max_length=150, blank=True)
	car_iac_6 = models.CharField(max_length=150, blank=True)
	car_iac_12 = models.CharField(max_length=150, blank=True)
	car_vit_b3_6 = models.CharField(max_length=150, blank=True)
	car_vit_b3_12 = models.CharField(max_length=150, blank=True)
	car_nitrato_6 = models.CharField(max_length=150, blank=True)
	car_nitrato_12 = models.CharField(max_length=150, blank=True)
	car_antiplaq_6 = models.CharField(max_length=150, blank=True)
	car_antiplaq_12 = models.CharField(max_length=150, blank=True)
	car_acido_acetil_6 = models.CharField(max_length=150, blank=True)
	car_acido_acetil_12 = models.CharField(max_length=150, blank=True)
	car_estatina_6 = models.CharField(max_length=150, blank=True)
	car_estatina_12 = models.CharField(max_length=150, blank=True)
	car_sab_6 = models.CharField(max_length=150, blank=True)
	car_sab_12 = models.CharField(max_length=150, blank=True)
	inf_sepsis_cuantos = models.CharField(max_length=150, blank=True)
	inf_sepsis_6 = models.CharField(max_length=150, blank=True)
	inf_sepsis_12 = models.CharField(max_length=150, blank=True)
	inf_neumonia_cuantos = models.CharField(max_length=150, blank=True)
	inf_neumonia_6 = models.CharField(max_length=150, blank=True)
	inf_neumonia_12 = models.CharField(max_length=150, blank=True)
	inf_vias_cuantos = models.CharField(max_length=150, blank=True)
	inf_vias_6 = models.CharField(max_length=150, blank=True)
	inf_vias_12 = models.CharField(max_length=150, blank=True)
	inf_ptb_cuantos = models.CharField(max_length=150, blank=True)
	inf_ptb_6 = models.CharField(max_length=150, blank=True)
	inf_ptv_12 = models.CharField(max_length=150, blank=True)
	inf_fungi_cuantos = models.CharField(max_length=150, blank=True)
	inf_fungi_6 = models.CharField(max_length=150, blank=True)
	inf_fungi_12 = models.CharField(max_length=150, blank=True)
	tx = models.TextField()
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'tratamiento'

class ComorbilidadesTx(models.Model):
	"""Datos del Comorbilidades"""
	folio = models.CharField(max_length=150)
	ment_depre_cual = models.CharField(max_length=150)
	ment_depre_6 = models.CharField(max_length=150)
	ment_depre_12 = models.CharField(max_length=150)
	ment_ansi_cual = models.CharField(max_length=150)
	ment_ansi_6 = models.CharField(max_length=150)
	ment_ansi_12 = models.CharField(max_length=150)
	ment_psico_cual = models.CharField(max_length=150)
	ment_psico_6 = models.CharField(max_length=150)
	ment_psico_12 = models.CharField(max_length=150)
	ot_cr_cual = models.CharField(max_length=150)
	ot_cr_6 = models.CharField(max_length=150)
	ot_cr_12 = models.CharField(max_length=150)
	ot_otra1_cual = models.CharField(max_length=150)
	ot_otra1_6 = models.CharField(max_length=150)
	ot_otra1_12 = models.CharField(max_length=150)
	ot_otra2_cual = models.CharField(max_length=150)
	ot_otra2_6 = models.CharField(max_length=150)
	ot_otra2_12 = models.CharField(max_length=150)
	tx = models.TextField()
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'comorbilidades_tx'

class Complicaciones(models.Model):
	"""Datos del Complicaciones"""
	folio = models.CharField(max_length=150)
	cual_1 = models.CharField(max_length=150)
	hosp_si_1 = models.CharField(max_length=150)
	hosp_eventos_1 = models.CharField(max_length=150)
	hosp_duracion_1 = models.CharField(max_length=150)
	espe_si_1 = models.CharField(max_length=150)
	espe_eventos_1 = models.CharField(max_length=150)
	espe_duracion_1 = models.CharField(max_length=150)
	otras_visitas_cual_1 = models.CharField(max_length=150)
	otras_visitas_si_1 = models.CharField(max_length=150)
	otras_visitas_eventos_1 = models.CharField(max_length=150)
	otras_visitas_duracion_1 = models.CharField(max_length=150)
	proc_1 = models.CharField(max_length=150)
	proc_si_1 = models.CharField(max_length=150)
	proc_eventos_1 = models.CharField(max_length=150)
	proc_duracion_1 = models.CharField(max_length=150)
	tx_1 = models.CharField(max_length=150)
	tx_posologia_1 = models.CharField(max_length=150)
	tx_si_1 = models.CharField(max_length=150)
	tx_eventos_1 = models.CharField(max_length=150)
	tx_duracion_1 = models.CharField(max_length=150)
	cual_2 = models.CharField(max_length=150)
	hosp_si_2 = models.CharField(max_length=150)
	hosp_eventos_2 = models.CharField(max_length=150)
	hosp_duracion_2 = models.CharField(max_length=150)
	espe_si_2 = models.CharField(max_length=150)
	espe_eventos_2 = models.CharField(max_length=150)
	espe_duracion_2 = models.CharField(max_length=150)
	otras_visitas_cual_2 = models.CharField(max_length=150)
	otras_visitas_si_2 = models.CharField(max_length=150)
	otras_visitas_eventos_2 = models.CharField(max_length=150)
	otras_visitas_duracion_2 = models.CharField(max_length=150)
	proc_2 = models.CharField(max_length=150)
	proc_si_2 = models.CharField(max_length=150)
	proc_eventos_2 = models.CharField(max_length=150)
	proc_duracion_2 = models.CharField(max_length=150)
	tx_2 = models.CharField(max_length=150)
	tx_posologia_2 = models.CharField(max_length=150)
	tx_si_2 = models.CharField(max_length=150)
	tx_eventos_2 = models.CharField(max_length=150)
	tx_duracion_2 = models.CharField(max_length=150)
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'complicaciones'

class TxCompleto(models.Model):
	"""docstring for Tx"""
	folio = models.CharField(max_length=150)
	clase = models.CharField(max_length=150)
	tratamiento = models.CharField(max_length=150)
	meses = models.CharField(max_length=150)
	fecha = models.CharField(max_length=150)
	dosis = models.CharField(max_length=150)
	c_horas = models.CharField(max_length=150)
	d_horas = models.CharField(max_length=150)
	intervalos = models.CharField(max_length=150)
	n_ciclos = models.CharField(max_length=150)
	cateterismo = models.BooleanField()
	hora_guardado = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'tx_completo'

class LabCompleto(models.Model):
	"""docstring for Lab"""
	folio = models.CharField(max_length=150)
	prueba = models.CharField(max_length=150)
	mes = models.CharField(max_length=150)
	fecha = models.CharField(max_length=150)
	resultado = models.CharField(max_length=150)
	class Meta:
		db_table = 'lab_completo'
		