#encoding:utf-8

from django.db import models

# Create your models here.

class RegEnt(models.Model):
    usuario = models.TextField(blank=True) # This field type is a guess.
    fecha_registro = models.TextField(blank=True) # This field type is a guess.
    hora_registro = models.TextField(blank=True) # This field type is a guess.
    tipo_registro = models.TextField(blank=True) # This field type is a guess.
    ip = models.TextField(blank=True) # This field type is a guess.
    class Meta:
        db_table = 'registro'

class Entrevistado(models.Model):
	"""Datos del Entrevistado"""
	folio = models.IntegerField()
	monitor_clinico = models.CharField(max_length=150)
	supervisor = models.CharField(max_length=150)
	fecha_llenado = models.IntegerField()
	nombre_medico = models.CharField(max_length=150)
	especialidad = models.CharField(max_length=150)
	pais = models.CharField(max_length=150)
	institucion_publica = models.CharField(max_length=150)
	institucion_privada = models.CharField(max_length=150)
	telefono = models.IntegerField()
	email = models.IntegerField()
	class Meta:
		db_table = 'entrevistado'
		
class Seleccion(models.Model):
	"""Datos del Seleccion"""
	folio = models.IntegerField()
	espe_medica = models.CharField(max_length=150)
	tiempo_endo = models.IntegerField()
	cushing_actual_tx = models.IntegerField()
	cushing_cm_12m = models.IntegerField()
	examen_orina_2 = models.IntegerField()
	examen_orina_1 = models.IntegerField()
	examen_orina_0 = models.IntegerField()
	class Meta:
		db_table = 'seleccion'

class Control(models.Model):
	"""Datos del Control"""
	folio = models.IntegerField()
	control_alto = models.IntegerField()
	control_bajo = models.IntegerField()
	control_medio = models.IntegerField()
	corti_libre_orina = models.CharField(max_length=150)
	hormona_adreno = models.CharField(max_length=150)
	sintomas_paciente = models.CharField(max_length=150)
	class Meta:
		db_table = 'control'

class Generales(models.Model):
	"""Datos del Generales"""
	folio = models.IntegerField()
	edad = models.IntegerField()
	sexo = models.CharField(max_length=150)
	peso = models.IntegerField()
	talla = models.IntegerField()
	imc = models.IntegerField()
	fecha_diag = models.DateField(auto_now=False)
	class Meta:
		db_table = 'generales'

# Por generar en el excel


class Sintomas(models.Model):
	"""Datos del Sintomas"""
	folio = models.IntegerField()
	cara_luna_6 = models.IntegerField()
	cara_luna_12 = models.IntegerField()
	ojos_jinchados_6 = models.IntegerField()
	ojos_jinchados_12 = models.IntegerField()
	tez_purpuras_6 = models.IntegerField()
	tez_purpuras_12 = models.IntegerField()
	acne_6 = models.IntegerField()
	acne_12 = models.IntegerField()
	estrias_6 = models.IntegerField()
	estrias_12 = models.IntegerField()
	moretones_6 = models.IntegerField()
	moretones_12 = models.IntegerField()
	aumento_abdomen_6 = models.IntegerField()
	aumento_abdomen_12 = models.IntegerField()
	joroba_6 = models.IntegerField()
	joroba_12 = models.IntegerField()
	temperatura_baja_6 = models.IntegerField()
	temperatura_baja_12 = models.IntegerField()
	sensibilidad_frio_6 = models.IntegerField()
	sensibilidad_frio_12 = models.IntegerField()
	fatiga_6 = models.IntegerField()
	fatiga_12 = models.IntegerField()
	osteopenia_6 = models.IntegerField()
	osteopenia_12 = models.IntegerField()
	osteoporosis_6 = models.IntegerField()
	osteoporosis_12 = models.IntegerField()
	ablan_col_vertebral_6 = models.IntegerField()
	ablan_col_vertebral_12 = models.IntegerField()
	dolores_espalda_6 = models.IntegerField()
	dolores_espalda_12 = models.IntegerField()
	fracturas_6 = models.IntegerField()
	fracturas_12 = models.IntegerField()
	debilidad_muscular_6 = models.IntegerField()
	debilidad_muscular_12 = models.IntegerField()
	debilidad_extrem_6 = models.IntegerField()
	debilidad_extrem_12 = models.IntegerField()
	hirsutismo_6 = models.IntegerField()
	hirsutismo_12 = models.IntegerField()
	ciclo_mesn_6 = models.IntegerField()
	ciclo_mesn_12 = models.IntegerField()
	infertilidad_6 = models.IntegerField()
	infertilidad_12 = models.IntegerField()
	disminucion_sexual_6 = models.IntegerField()
	disminucion_sexual_12 = models.IntegerField()
	impotencia_6 = models.IntegerField()
	impotencia_12 = models.IntegerField()
	deficit_cognitivos_6 = models.IntegerField()
	deficit_cognitivos_12 = models.IntegerField()
	otro1_cual = models.CharField(max_length=150)
	otro1_6 = models.IntegerField()
	otro1_12 = models.IntegerField()
	otro2_cual = models.CharField(max_length=150)
	otro2_6 = models.IntegerField()
	otro2_12 = models.IntegerField()

	class Meta:
		db_table = 'sintomas'

class Comorbilidades(models.Model):
	"""Datos del Generales"""
	folio = models.IntegerField()
	dm1_6 = models.IntegerField()
	dm1_12 = models.IntegerField()
	dm2_6 = models.IntegerField()
	dm2_12 = models.IntegerField()
	sind_met_6 = models.IntegerField()
	sind_met_12 = models.IntegerField()
	int_glucosa_6 = models.IntegerField()
	int_glucosa_12 = models.IntegerField()
	obeisdad_6 = models.IntegerField()
	obeisdad_12 = models.IntegerField()
	hipertension_6 = models.IntegerField()
	hipertension_12 = models.IntegerField()
	colesterol_6 = models.IntegerField()
	colesterol_12 = models.IntegerField()
	trombosis_6 = models.IntegerField()
	trombosis_12 = models.IntegerField()
	infarto_miocardio_6 = models.IntegerField()
	infarto_miocardio_12 = models.IntegerField()
	angina_pecho_6 = models.IntegerField()
	angina_pecho_12 = models.IntegerField()
	cardiopatia_6 = models.IntegerField()
	cardiopatia_12 = models.IntegerField()
	cerebrovascular_6 = models.IntegerField()
	cerebrovascular_12 = models.IntegerField()
	isquemia_6 = models.IntegerField()
	isquemia_12 = models.IntegerField()
	sepsis_6 = models.IntegerField()
	sepsis_12 = models.IntegerField()
	neumonia_6 = models.IntegerField()
	neumonia_12 = models.IntegerField()
	vias_urinarias_6 = models.IntegerField()
	vias_urinarias_12 = models.IntegerField()
	pytb_6 = models.IntegerField()
	pytb_12 = models.IntegerField()
	fungicas_6 = models.IntegerField()
	fungicas_12 = models.IntegerField()
	depresion_6 = models.IntegerField()
	depresion_12 = models.IntegerField()
	ansiedad_6 = models.IntegerField()
	ansiedad_12 = models.IntegerField()
	psicosis_6 = models.IntegerField()
	psicosis_12 = models.IntegerField()
	cr_6 = models.IntegerField()
	cr_12 = models.IntegerField()
	otro1_cual = models.CharField(max_length=150)
	otro1_6 = models.IntegerField()
	otro1_12 = models.IntegerField()
	otro2_cual = models.CharField(max_length=150)
	otro2_6 = models.IntegerField()
	otro2_12 = models.IntegerField()

	class Meta:
		db_table = 'comorbilidades'

class Especialista(models.Model):
	"""Datos del Especialista"""
	folio = models.IntegerField()
	endo_1_mes = models.IntegerField()
	endo_2_mes = models.IntegerField()
	endo_3_mes = models.IntegerField()
	endo_4_mes = models.IntegerField()
	endo_5_mes = models.IntegerField()
	endo_6_mes = models.IntegerField()
	endo_7_mes = models.IntegerField()
	endo_8_mes = models.IntegerField()
	endo_9_mes = models.IntegerField()
	endo_10_mes = models.IntegerField()
	endo_11_mes = models.IntegerField()
	endo_12_mes = models.IntegerField()
	inter_1_mes = models.IntegerField()
	inter_2_mes = models.IntegerField()
	inter_3_mes = models.IntegerField()
	inter_4_mes = models.IntegerField()
	inter_5_mes = models.IntegerField()
	inter_6_mes = models.IntegerField()
	inter_7_mes = models.IntegerField()
	inter_8_mes = models.IntegerField()
	inter_9_mes = models.IntegerField()
	inter_10_mes = models.IntegerField()
	inter_11_mes = models.IntegerField()
	inter_12_mes = models.IntegerField()
	cx_1_mes = models.IntegerField()
	cx_2_mes = models.IntegerField()
	cx_3_mes = models.IntegerField()
	cx_4_mes = models.IntegerField()
	cx_5_mes = models.IntegerField()
	cx_6_mes = models.IntegerField()
	cx_7_mes = models.IntegerField()
	cx_8_mes = models.IntegerField()
	cx_9_mes = models.IntegerField()
	cx_10_mes = models.IntegerField()
	cx_11_mes = models.IntegerField()
	cx_12_mes = models.IntegerField()
	urg_1_mes = models.IntegerField()
	urg_2_mes = models.IntegerField()
	urg_3_mes = models.IntegerField()
	urg_4_mes = models.IntegerField()
	urg_5_mes = models.IntegerField()
	urg_6_mes = models.IntegerField()
	urg_7_mes = models.IntegerField()
	urg_8_mes = models.IntegerField()
	urg_9_mes = models.IntegerField()
	urg_10_mes = models.IntegerField()
	urg_11_mes = models.IntegerField()
	urg_12_mes = models.IntegerField()
	otro1_cual = models.CharField(max_length=150)
	otro1_1_mes = models.IntegerField()
	otro1_2_mes = models.IntegerField()
	otro1_3_mes = models.IntegerField()
	otro1_4_mes = models.IntegerField()
	otro1_5_mes = models.IntegerField()
	otro1_6_mes = models.IntegerField()
	otro1_7_mes = models.IntegerField()
	otro1_8_mes = models.IntegerField()
	otro1_9_mes = models.IntegerField()
	otro1_10_mes = models.IntegerField()
	otro1_11_mes = models.IntegerField()
	otro1_12_mes = models.IntegerField()
	otro2_cual = models.CharField(max_length=150)
	otro2_1_mes = models.IntegerField()
	otro2_2_mes = models.IntegerField()
	otro2_3_mes = models.IntegerField()
	otro2_4_mes = models.IntegerField()
	otro2_5_mes = models.IntegerField()
	otro2_6_mes = models.IntegerField()
	otro2_7_mes = models.IntegerField()
	otro2_8_mes = models.IntegerField()
	otro2_9_mes = models.IntegerField()
	otro2_10_mes = models.IntegerField()
	otro2_11_mes = models.IntegerField()
	otro2_12_mes = models.IntegerField()
	class Meta:
		db_table = 'especialista'

class Hospitalizacion(models.Model):
	"""Datos del Hospitalizacion"""
	folio = models.IntegerField()
	hosp_1_mes = models.IntegerField()
	hosp_2_mes = models.IntegerField()
	hosp_3_mes = models.IntegerField()
	hosp_4_mes = models.IntegerField()
	hosp_5_mes = models.IntegerField()
	hosp_6_mes = models.IntegerField()
	hosp_7_mes = models.IntegerField()
	hosp_8_mes = models.IntegerField()
	hosp_9_mes = models.IntegerField()
	hosp_10_mes = models.IntegerField()
	hosp_11_mes = models.IntegerField()
	hosp_12_mes = models.IntegerField()
	ci_1_mes = models.IntegerField()
	ci_2_mes = models.IntegerField()
	ci_3_mes = models.IntegerField()
	ci_4_mes = models.IntegerField()
	ci_5_mes = models.IntegerField()
	ci_6_mes = models.IntegerField()
	ci_7_mes = models.IntegerField()
	ci_8_mes = models.IntegerField()
	ci_9_mes = models.IntegerField()
	ci_10_mes = models.IntegerField()
	ci_11_mes = models.IntegerField()
	ci_12_mes = models.IntegerField()

	class Meta:
		db_table = 'hospitalizacion'

class Laboratorio(models.Model):
	"""Datos del Laboratorio"""
	folio = models.IntegerField()
	clo_no_1_mes = models.IntegerField()
	clo_valor_1_mes = models.IntegerField()
	clo_no_2_mes = models.IntegerField()
	clo_valor_2_mes = models.IntegerField()
	clo_no_3_mes = models.IntegerField()
	clo_valor_3_mes = models.IntegerField()
	clo_no_4_mes = models.IntegerField()
	clo_valor_4_mes = models.IntegerField()
	clo_no_5_mes = models.IntegerField()
	clo_valor_5_mes = models.IntegerField()
	clo_no_6_mes = models.IntegerField()
	clo_valor_6_mes = models.IntegerField()
	clo_no_7_mes = models.IntegerField()
	clo_valor_7_mes = models.IntegerField()
	clo_no_8_mes = models.IntegerField()
	clo_valor_8_mes = models.IntegerField()
	clo_no_9_mes = models.IntegerField()
	clo_valor_9_mes = models.IntegerField()
	clo_no_10_mes = models.IntegerField()
	clo_valor_10_mes = models.IntegerField()
	clo_no_11_mes = models.IntegerField()
	clo_valor_11_mes = models.IntegerField()
	clo_no_12_mes = models.IntegerField()
	clo_valor_12_mes = models.IntegerField()
	ha_no_1_mes = models.IntegerField()
	ha_valor_1_mes = models.IntegerField()
	ha_no_2_mes = models.IntegerField()
	ha_valor_2_mes = models.IntegerField()
	ha_no_3_mes = models.IntegerField()
	ha_valor_3_mes = models.IntegerField()
	ha_no_4_mes = models.IntegerField()
	ha_valor_4_mes = models.IntegerField()
	ha_no_5_mes = models.IntegerField()
	ha_valor_5_mes = models.IntegerField()
	ha_no_6_mes = models.IntegerField()
	ha_valor_6_mes = models.IntegerField()
	ha_no_7_mes = models.IntegerField()
	ha_valor_7_mes = models.IntegerField()
	ha_no_8_mes = models.IntegerField()
	ha_valor_8_mes = models.IntegerField()
	ha_no_9_mes = models.IntegerField()
	ha_valor_9_mes = models.IntegerField()
	ha_no_10_mes = models.IntegerField()
	ha_valor_10_mes = models.IntegerField()
	ha_no_11_mes = models.IntegerField()
	ha_valor_11_mes = models.IntegerField()
	ha_no_12_mes = models.IntegerField()
	ha_valor_12_mes = models.IntegerField()
	# Columnas no contabilizadas en el excel
	control_1_mes = models.IntegerField()
	control_2_mes = models.IntegerField()
	control_3_mes = models.IntegerField()
	control_4_mes = models.IntegerField()
	control_5_mes = models.IntegerField()
	control_6_mes = models.IntegerField()
	control_7_mes = models.IntegerField()
	control_8_mes = models.IntegerField()
	control_9_mes = models.IntegerField()
	control_10_mes = models.IntegerField()
	control_11_mes = models.IntegerField()
	control_12_mes = models.IntegerField()
	# Terminan las columnas no coontabilizadas en excel
	psd_si_6 = models.IntegerField()
	psd_pruebas_6 = models.IntegerField()
	psd_si_12 = models.IntegerField()
	psd_pruebas_12 = models.IntegerField()
	acth_si_6 = models.IntegerField()
	acth_pruebas_6 = models.IntegerField()
	acth_si_12 = models.IntegerField()
	acth_pruebas_12 = models.IntegerField()
	metirapona_si_6 = models.IntegerField()
	metirapona_pruebas_6 = models.IntegerField()
	metirapona_si_12 = models.IntegerField()
	metirapona_pruebas_12 = models.IntegerField()
	crh_si_6 = models.IntegerField()
	crh_pruebas_6 = models.IntegerField()
	crh_si_12 = models.IntegerField()
	crh_pruebas_12 = models.IntegerField()
	seno_petroso_si_6 = models.IntegerField()
	seno_petroso_pruebas_6 = models.IntegerField()
	seno_petroso_si_12 = models.IntegerField()
	seno_petroso_pruebas_12 = models.IntegerField()
	tomografia_si_6 = models.IntegerField()
	tomografia_pruebas_6 = models.IntegerField()
	tomografia_si_12 = models.IntegerField()
	tomografia_pruebas_12 = models.IntegerField()
	res_magnetica_si_6 = models.IntegerField()
	res_magnetica_pruebas_6 = models.IntegerField()
	res_magnetica_si_12 = models.IntegerField()
	res_magnetica_pruebas_12 = models.IntegerField()
	otro1_cual = models.CharField(max_length=150)
	otro1_si_6 = models.IntegerField()
	otro1_pruebas_6 = models.IntegerField()
	otro1_si_12 = models.IntegerField()
	otro1_pruebas_12 = models.IntegerField()
	otro2_cual = models.CharField(max_length=150)
	otro2_si_6 = models.IntegerField()
	otro2_pruebas_6 = models.IntegerField()
	otro2_si_12 = models.IntegerField()
	otro2_pruebas_12 = models.IntegerField()

	class Meta:
		db_table = 'laboratorio'

class Intervenciones(models.Model):
	"""Datos del Intervenciones"""
	folio = models.IntegerField()
	rx_si_6 = models.IntegerField()
	rx_hipo_comp_6 = models.IntegerField()
	rx_hipo_veces_6 = models.IntegerField()
	rx_cerebro_comp_6 = models.IntegerField()
	rx_cerebro_veces_6 = models.IntegerField()
	rx_otras_comp_6 = models.IntegerField()
	rx_otras_veces_6 = models.IntegerField()
	radiocirugia_si_6 = models.IntegerField()
	radiocirugia_hipo_comp_6 = models.IntegerField()
	radiocirugia_hipo_veces_6 = models.IntegerField()
	radiocirugia_visual_comp_6 = models.IntegerField()
	radiocirugia_visual_veces_6 = models.IntegerField()
	radiocirugia_craneal_comp_6 = models.IntegerField()
	radiocirugia_craneal_veces_6 = models.IntegerField()
	radiocirugia_otras_comp_6 = models.IntegerField()
	radiocirugia_otras_veces_6 = models.IntegerField()
	cirugia_si_6 = models.IntegerField()
	cirugia_hormo_comp_6 = models.IntegerField()
	cirugia_hormo_veces_6 = models.IntegerField()
	cirugia_diabetes_comp_6 = models.IntegerField()
	cirugia_diabetes_veces_6 = models.IntegerField()
	cirugia_cerebro_comp_6 = models.IntegerField()
	cirugia_cerebro_veces_6 = models.IntegerField()
	cirugia_visual_comp_6 = models.IntegerField()
	cirugia_visual_veces_6 = models.IntegerField()
	cirugia_menin_comp_6 = models.IntegerField()
	cirugia_menin_veces_6 = models.IntegerField()
	cirugia_cefalo_comp_6 = models.IntegerField()
	cirugia_cefalo_veces_6 = models.IntegerField()
	cirugia_otras_comp_6 = models.IntegerField()
	cirugia_otras_veces_6 = models.IntegerField()
	adrena_si_6 = models.IntegerField()
	adrena_nelson_comp_6 = models.IntegerField()
	adrena_nelson_veces_6 = models.IntegerField()
	adrena_otras_comp_6 = models.IntegerField()
	adrena_otras_veces_6 = models.IntegerField()
	rx_si_12 = models.IntegerField()
	rx_hipo_comp_12 = models.IntegerField()
	rx_hipo_veces_12 = models.IntegerField()
	rx_cerebro_comp_12 = models.IntegerField()
	rx_cerebro_veces_12 = models.IntegerField()
	rx_otras_comp_12 = models.IntegerField()
	rx_otras_veces_12 = models.IntegerField()
	radiocirugia_si_12 = models.IntegerField()
	radiocirugia_hipo_comp_12 = models.IntegerField()
	radiocirugia_hipo_veces_12 = models.IntegerField()
	radiocirugia_visual_comp_12 = models.IntegerField()
	radiocirugia_visual_veces_12 = models.IntegerField()
	radiocirugia_craneal_comp_12 = models.IntegerField()
	radiocirugia_craneal_veces_12 = models.IntegerField()
	radiocirugia_otras_comp_12 = models.IntegerField()
	radiocirugia_otras_veces_12 = models.IntegerField()
	cirugia_si_12 = models.IntegerField()
	cirugia_hormo_comp_12 = models.IntegerField()
	cirugia_hormo_veces_12 = models.IntegerField()
	cirugia_diabetes_comp_12 = models.IntegerField()
	cirugia_diabetes_veces_12 = models.IntegerField()
	cirugia_cerebro_comp_12 = models.IntegerField()
	cirugia_cerebro_veces_12 = models.IntegerField()
	cirugia_visual_comp_12 = models.IntegerField()
	cirugia_visual_veces_12 = models.IntegerField()
	cirugia_menin_comp_12 = models.IntegerField()
	cirugia_menin_veces_12 = models.IntegerField()
	cirugia_cefalo_comp_12 = models.IntegerField()
	cirugia_cefalo_veces_12 = models.IntegerField()
	cirugia_otras_comp_12 = models.IntegerField()
	cirugia_otras_veces_12 = models.IntegerField()
	adrena_si_12 = models.IntegerField()
	adrena_nelson_comp_12 = models.IntegerField()
	adrena_nelson_veces_12 = models.IntegerField()
	adrena_otras_comp_12 = models.IntegerField()
	adrena_otras_veces_12 = models.IntegerField()

	class Meta:
		db_table = 'inteervenciones'

class Tratamiento(models.Model):
	"""Datos del Tratamiento"""
	folio = models.IntegerField()
	keto_6 = models.IntegerField()
	keto_12 = models.IntegerField()
	caber_6 = models.IntegerField()
	caber_12 = models.IntegerField()
	mife_6 = models.IntegerField()
	mife_12 = models.IntegerField()
	otro1_cual = models.CharField(max_length=150)
	otro1_6 = models.IntegerField()
	otro1_12 = models.IntegerField()
	otro2_cual = models.CharField(max_length=150)
	otro2_6 = models.IntegerField()
	otro2_12 = models.IntegerField()
	otro3_cual = models.CharField(max_length=150)
	otro3_6 = models.IntegerField()
	otro3_12 = models.IntegerField()
	metfo_6 = models.IntegerField()
	metfo_12 = models.IntegerField()
	sulfo_6 = models.IntegerField()
	sulfo_12 = models.IntegerField()
	tiazo_6 = models.IntegerField()
	tiazo_12 = models.IntegerField()
	dpp4_6 = models.IntegerField()
	dpp4_12 = models.IntegerField()
	glp1_6 = models.IntegerField()
	glp1_12 = models.IntegerField()
	insu_rapida_6 = models.IntegerField()
	insu_rapida_12 = models.IntegerField()
	insu_lenta_6 = models.IntegerField()
	insu_lenta_12 = models.IntegerField()
	ieca_6 = models.IntegerField()
	ieca_12 = models.IntegerField()
	bra_6 = models.IntegerField()
	bra_12 = models.IntegerField()
	beta_bloq_6 = models.IntegerField()
	beta_bloq_12 = models.IntegerField()
	fibratos_6 = models.IntegerField()
	fibratos_12 = models.IntegerField()
	bcc_6 = models.IntegerField()
	bcc_12 = models.IntegerField()
	diuretico_6 = models.IntegerField()
	diuretico_12 = models.IntegerField()
	iac_6 = models.IntegerField()
	iac_12 = models.IntegerField()
	vit_b3_6 = models.IntegerField()
	vit_b3_12 = models.IntegerField()
	nitrato_6 = models.IntegerField()
	nitrato_12 = models.IntegerField()
	antiplaq_6 = models.IntegerField()
	antiplaq_12 = models.IntegerField()
	acido_acetil_6 = models.IntegerField()
	acido_acetil_12 = models.IntegerField()
	estatina_6 = models.IntegerField()
	estatina_12 = models.IntegerField()
	sab_6 = models.IntegerField()
	sab_12 = models.IntegerField()
	sepsis_cual = models.IntegerField()
	sepsis_6 = models.IntegerField()
	sepsis_12 = models.IntegerField()
	neumonia_cual = models.IntegerField()
	neumonia_6 = models.IntegerField()
	neumonia_12 = models.IntegerField()
	vias_cual = models.IntegerField()
	vias_6 = models.IntegerField()
	vias_12 = models.IntegerField()
	ptb_cual = models.IntegerField()
	ptb_6 = models.IntegerField()
	ptv_12 = models.IntegerField()
	fungi_cual = models.IntegerField()
	fungi_6 = models.IntegerField()
	fungi_12 = models.IntegerField()

	class Meta:
		db_table = 'tratamiento'

class ComorbilidadesTx(models.Model):
	"""Datos del Comorbilidades"""
	folio = models.IntegerField()
	depre_cual = models.CharField(max_length=150)
	depre_6 = models.IntegerField()
	depre_12 = models.IntegerField()
	ansi_cual = models.CharField(max_length=150)
	ansi_6 = models.IntegerField()
	ansi_12 = models.IntegerField()
	psico_cual = models.CharField(max_length=150)
	psico_6 = models.IntegerField()
	psico_12 = models.IntegerField()
	cr_cual = models.CharField(max_length=150)
	cr_6 = models.IntegerField()
	cr_12 = models.IntegerField()
	otra1_cual = models.CharField(max_length=150)
	otra1_6 = models.IntegerField()
	otra1_12 = models.IntegerField()
	otra2_cual = models.CharField(max_length=150)
	otra2_6 = models.IntegerField()
	otra2_12 = models.IntegerField()

	class Meta:
		db_table = 'comorbilidades_tx'

class Complicaciones(models.Model):
	"""Datos del Complicaciones"""
	folio = models.IntegerField()
	cual_1 = models.CharField(max_length=150)
	hosp_si_1 = models.CharField(max_length=150)
	hosp_eventos_1 = models.CharField(max_length=150)
	hosp_duracion_1 = models.CharField(max_length=150)
	espe_si_1 = models.CharField(max_length=150)
	espe_eventos_1 = models.CharField(max_length=150)
	espe_duracion_1 = models.CharField(max_length=150)
	otras_visitas_cual_1 = models.CharField(max_length=150)
	otras_visitas_si_1 = models.CharField(max_length=150)
	otras_visitas_eventos_1 = models.CharField(max_length=150)
	otras_visitas_duracion_1 = models.CharField(max_length=150)
	proc_1 = models.CharField(max_length=150)
	proc_si_1 = models.CharField(max_length=150)
	proc_eventos_1 = models.CharField(max_length=150)
	proc_duracion_1 = models.CharField(max_length=150)
	tx_1 = models.CharField(max_length=150)
	tx_posologia_1 = models.CharField(max_length=150)
	tx_si_1 = models.CharField(max_length=150)
	tx_eventos_1 = models.CharField(max_length=150)
	tx_duracion_1 = models.CharField(max_length=150)
	cual_2 = models.CharField(max_length=150)
	hosp_si_2 = models.CharField(max_length=150)
	hosp_eventos_2 = models.CharField(max_length=150)
	hosp_duracion_2 = models.CharField(max_length=150)
	espe_si_2 = models.CharField(max_length=150)
	espe_eventos_2 = models.CharField(max_length=150)
	espe_duracion_2 = models.CharField(max_length=150)
	otras_visitas_cual_2 = models.CharField(max_length=150)
	otras_visitas_si_2 = models.CharField(max_length=150)
	otras_visitas_eventos_2 = models.CharField(max_length=150)
	otras_visitas_duracion_2 = models.CharField(max_length=150)
	proc_2 = models.CharField(max_length=150)
	proc_si_2 = models.CharField(max_length=150)
	proc_eventos_2 = models.CharField(max_length=150)
	proc_duracion_2 = models.CharField(max_length=150)
	tx_2 = models.CharField(max_length=150)
	tx_posologia_2 = models.CharField(max_length=150)
	tx_si_2 = models.CharField(max_length=150)
	tx_eventos_2 = models.CharField(max_length=150)
	tx_duracion_2 = models.CharField(max_length=150)

	class Meta:
		db_table = 'complicaciones'